----item----
version: 1
id: {ED909233-6A4B-4438-B067-6EC791D0931A}
database: master
path: /sitecore/content/Home/Articles/2019/01/Sitecore ERROR  Exception When Executing Agent Aggregation
parent: {2EDB6177-75F9-4852-9307-671A96FC9335}
name: Sitecore ERROR  Exception When Executing Agent Aggregation
master: {00000000-0000-0000-0000-000000000000}
template: {DCE93757-77A5-4B68-A276-227CFB6960F4}
templatekey: Article
created: 20190125T192213Z

----version----
language: en
version: 1
revision: 91c02156-3373-4652-aeab-214326dfeb24

----field----
field: {42F95762-2E8F-4AA7-94D4-A35D6626B7B9}
name: Article Type
key: article type
content-length: 38

{E4BF1B57-1135-45AD-8C23-8E4FE29B9B15}
----field----
field: {EC425F3B-1B12-48E2-A4CF-33DADEDA8465}
name: Display Date
key: display date
content-length: 15

20190125T000000
----field----
field: {917E43EE-4138-427A-8297-C11F04C31EC2}
name: Link
key: link
content-length: 144

<link target="_blank" url="https://sitecorejourney.nileshthakkar.in/2019/01/sitecore-error-exception-when-executing.html" linktype="external" />
----field----
field: {2AEE6781-8B14-4AAE-A50F-C5F03655984C}
name: Title
key: title
content-length: 59

Sitecore ERROR : Exception When Executing Agent Aggregation
----field----
field: {FFA57B49-7D8B-41B8-AEB5-62EAF164F9B7}
name: Description
key: description
content-length: 7423

<div dir="ltr" style="text-align: left;" trbidi="on">Are you facing below mentioned xConnect error? Not able to find out the possible cause and fix?<br /><div class="separator" style="clear: both; text-align: center;"><br /></div><div class="separator" style="clear: both; text-align: center;"><a href="https://4.bp.blogspot.com/-FNliYCfc4Vw/XErQJArxePI/AAAAAAAAC1E/NjdYg942zG8-6RZVtAHc9KmpG17-z0TIwCLcBGAs/s1600/sitecore%2Bxconnect%2Berror.jpeg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="184" data-original-width="274" height="267" src="https://4.bp.blogspot.com/-FNliYCfc4Vw/XErQJArxePI/AAAAAAAAC1E/NjdYg942zG8-6RZVtAHc9KmpG17-z0TIwCLcBGAs/s400/sitecore%2Bxconnect%2Berror.jpeg" width="400" /></a></div><br /><br />Well, one of my colleague was struggling with this error on Processing Server. Log files were full of below mentioned error.<br /><br /><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 11pt;">8556 13:04:06 ERROR Exception when executing agent aggregation/aggregator Exception: Sitecore.XConnect.XdbCollectionUnavailableException Message: An error occurred while sending the request. Source: Sitecore.XConnect.Client at Sitecore.XConnect.Client.WebApi.CollectionBatchWebApiClient.&lt;ExecuteBatch&gt;d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.XConnect.Client.Operations.HttpOperationInvoker.&lt;Execute&gt;d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.XConnect.XdbContext.&lt;ExecuteBatchAsyncInternal&gt;d__79.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Sitecore.XConnect.XdbContext.&lt;ExecuteBatchAsyncInternal&gt;d__79.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.XConnect.XdbContext.&lt;ExecuteAsync&gt;d__72.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.XConnect.XdbContext.&lt;GetAsync&gt;d__35`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.Analytics.Processing.AsyncPoolScheduler`2.&lt;TryGetNextAsync&gt;d__14.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.Analytics.Aggregation.InteractionAggregationAgent.&lt;ExecuteCoreAsync&gt;d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.Analytics.Core.Agent.&lt;ExecuteAsync&gt;d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.Analytics.Core.AsyncBackgroundService.&lt;ExecuteAgentAsync&gt;d__22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.Analytics.Core.AsyncBackgroundService.&lt;RunAsync&gt;d__26.MoveNext() Nested Exception Exception: Sitecore.Xdb.Common.Web.ConnectionTimeoutException Message: A task was canceled. Source: Sitecore.Xdb.Common.Web at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.&lt;ExecuteAsync&gt;d__37.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.XConnect.Client.WebApi.CollectionBatchWebApiClient.&lt;ExecuteBatch&gt;d__11.MoveNext() Nested Exception Exception: System.Threading.Tasks.TaskCanceledException Message: A task was canceled. Source: mscorlib at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.&lt;ExecuteAsync&gt;d__37.MoveNext()</span><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 11pt;">&nbsp;</span><br /><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 11pt;"><br /></span><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 11pt;">This <b>seems Scaling issue</b>&nbsp;</span><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif;"><span style="font-size: 14px;">as the error was now completely disappeared after scaling up. So try scaling up your instance to get rid of such issue. Thanks to my colleague&nbsp;<u>Thom </u>for sharing this resoultion!</span></span><br /><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 14px;"><br /></span><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 14px;">Let me know if you find any other resolution.</span><br /><span style="font-family: &quot;segoe ui&quot; , &quot;helvetica neue&quot; , &quot;apple color emoji&quot; , &quot;segoe ui emoji&quot; , &quot;helvetica&quot; , &quot;arial&quot; , sans-serif; font-size: 14px;"><br /></span></div>
----field----
field: {52807595-0F8F-4B20-8D2A-CB71D28C6103}
name: __Owner
key: __owner
content-length: 18

extranet\Anonymous
----field----
field: {25BED78C-4957-4165-998A-CA1B52F67497}
name: __Created
key: __created
content-length: 16

20190125T192214Z
----field----
field: {5DD74568-4D4B-44C1-B513-0AF5F4CDA34F}
name: __Created by
key: __created by
content-length: 18

extranet\Anonymous
----field----
field: {8CDC337E-A112-42FB-BBB4-4143751E123F}
name: __Revision
key: __revision
content-length: 36

91c02156-3373-4652-aeab-214326dfeb24
----field----
field: {D9CF14B1-FA16-4BA6-9288-E8A174D4D522}
name: __Updated
key: __updated
content-length: 16

20190125T192215Z
----field----
field: {BADD9CF9-53E0-4D0C-BCC0-2D784C282F6A}
name: __Updated by
key: __updated by
content-length: 18

extranet\Anonymous
